---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/versions/?project_id=371767"
changelog_format: json

# Regex for Version
version: "{{ register_changelog.json['latest_version'][0:7] }}"

# Download URL
url: 'https://github.com/PowerShell/Win32-OpenSSH/releases/download/v{{ version }}p1-Beta/OpenSSH-Win32-v{{ version }}.msi'
url64: 'https://github.com/PowerShell/Win32-OpenSSH/releases/download/v{{ version }}p1-Beta/OpenSSH-Win64-v{{ version }}.msi'

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*urlPackage64\s*=\s*)('.*')
      replace: "$urlPackage64 = '{{ url64 }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"
    - regwxp: (^\s*[$]*checksumPackage64\s*=\s*)('.*')
      replace: "$checksumPackage64 = '{{ file_hash }}'"

# readme to description
readme:
  start: 4
  end: 28

# deploy
deploy:
  #- provider: chocolatey
  #  repository: "https://push.chocolatey.org/"
  #  key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"

  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.Win32-OpenSSH.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

  - provider: chocolatey
    repository: "https://packages.ocrcl.ch/"
    key: "{{ lookup('env', 'CHOCOWALL_PROD_API_KEY') }}"

# Notification
notifications:
  #- provider: mattermost
  #  url: "https://chat.open-circle.ch"
  #  key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
  #  channel: "notification-chocolatey"
